name: power_rangers
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.4.0

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0

  intl: ^0.16.0
  adobe_xd: ^1.0.0+1
  flutter_swiper: ^1.1.6
  fl_chart: ^0.12.2
  charts_flutter: ^0.9.0
  bezier_chart: ^1.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

